### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by pbbpage** [RoboJackets/rrt#19]
I'm interested in using this code to run my robot, which uses windows, unfortunately :( . How easy would this be, and do you have any suggestions?  Are there any particular C++ version dependencies?

**Comment by justbuchanan** [comment]
The only requirements are CMake, Eigen, and Qt, which are all available for Windows.  The CMake build files may be unable to find your installations of Eigen and Qt out of the box, so you may have to hard-code the paths or add some additional CMake logic for finding them.  Also, if you don't need the GUI and just want the RRT data structure, you can skip installing Qt.  Best of luck!
