### ISSUE TITLE
Error: Do not know how to extract

### ISSUE THREAD

**Issue by boonflies** [RoboJackets/rrt#32]
I get this error while I try to 'make'

CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:609 (message):
  error: do not know how to extract
  '/home/boon/Packages/RoboJackets_RRT/rrt/third_party/googletest/googletest'
  -- known types are .bz2, .tar, .tar.gz, .tgz and .zip
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1420 (_ep_write_extractfile_script)
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1805 (_ep_add_download_command)
  cmake/SetupGTest.cmake:4 (ExternalProject_Add)
  CMakeLists.txt:75 (include)
-- Configuring incomplete, errors occurred!
See also "/home/boon/Packages/RoboJackets_RRT/rrt/build/CMakeFiles/CMakeOutput.log".
make: *** [all] Error 1

**Comment by justbuchanan** [comment]
I think I've seen this come up before because of git submodules.  Try running `git submodule update` then rebuilding and see if it fixes your issue.

**Comment by Learningto** [comment]
Unfortunately,It can not work on my computer(ubuntu14.04)

**Comment by jgkamat** [comment]
@Learningto if you are having this same issue again, can you try running
`git submodule update --init` and trying again?
