### ISSUE TITLE
Fix docker caching issues

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/rrt#41]
As far as I can tell, things are setup correctly and I have the docker auth variables set in the circleci environment.  The build logs show that the image was pushed to the repo, but the docker hub page shows otherwise.

See [this build](https://circleci.com/gh/RoboJackets/rrt/45) and the [docker hub page](https://hub.docker.com/r/robojackets/rrt-baseimage/).

**Comment by jgkamat** [comment]
Was an authorisation issue. I'm going to add better error outputs when this happens in the future.
