### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by umerhuzaifa** [RoboJackets/rrt#43]
Hi,

I am running Ubuntu 14.0.4 and as I run make in the main folder, I get the following error:

`CMake Error at CMakeLists.txt:71 (get_filename_component):
  get_filename_component unknown component DIRECTORY
`

Kindly guide me what could be the problem here.

Thanks,
Umer

**Comment by jgkamat** [comment]
Have you installed all the dependencies (in the readme) and also initialized submodules with `git submodule update --init`?

**Comment by umerhuzaifa** [comment]
I figured it out .
I didn't do hit submodule -- init

Thanks,
Umer
