### ISSUE TITLE
error: do not know how to extract

### ISSUE THREAD

**Issue by pioneerbkh** [RoboJackets/rrt#45]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
cmake version 3.5.2
ninja version 0.1.3
The Compile message is...
-------------------------------------------
mkdir -p build
cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH="" -GNinja && ninja
-- Found Qt5: /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:964 (message):
  error: do not know how to extract
  '/home/travis-byun/WorkSpace_vim/rrt/rrt-master/third_party/googletest/googletest'
  -- known types are .7z, .tar, .tar.bz2, .tar.gz, .tar.xz, .tbz2, .tgz, .txz
  and .zip
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1909 (_ep_write_extractfile_script)
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  cmake/SetupGTest.cmake:5 (ExternalProject_Add)
  CMakeLists.txt:96 (include)

-- Configuring incomplete, errors occurred!
See also "/home/travis-byun/WorkSpace_vim/rrt/rrt-master/build/CMakeFiles/CMakeOutput.log".
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by jgkamat** [comment]
I think this is an error from missing submodules.

Can you try running:
`git submodule update --init`, and try compiling again?

Comment back what you find!

**Comment by pioneerbkh** [comment]
travis-byun@HCI:~/WorkSpace_vim/rrt/rrt-master$ git submodule update --init
travis-byun@HCI:~/WorkSpace_vim/rrt/rrt-master$ make
mkdir -p build
cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH="" -GNinja && ninja
-- Found Qt5: /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:964 (message):
  error: do not know how to extract
  '/home/travis-byun/WorkSpace_vim/rrt/rrt-master/third_party/googletest/googletest'
  -- known types are .7z, .tar, .tar.bz2, .tar.gz, .tar.xz, .tbz2, .tgz, .txz
  and .zip
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1909 (_ep_write_extractfile_script)
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  cmake/SetupGTest.cmake:5 (ExternalProject_Add)
  CMakeLists.txt:96 (include)


-- Configuring incomplete, errors occurred!
See also "/home/travis-byun/WorkSpace_vim/rrt/rrt-master/build/CMakeFiles/CMakeOutput.log".
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by jgkamat** [comment]
Hmm, that is pretty weird. Can you try running this command:

`git submodule sync && git submodule update --init`

Also, if that dosen't work, could you post the output of:
`git status`
and 
`git submodule`

**Comment by jgkamat** [comment]
also I noticed your path is: `~/WorkSpace_vim/rrt/rrt-master`

Can you cd up to the `~/WorkSpace_vim/rrt` folder and try these commands again?

**Comment by pioneerbkh** [comment]
I got something different messages
----------------------
travis-byun@HCI:~/WorkSpace_vim/rrt$ git submodule sync && git submodule update --init
travis-byun@HCI:~/WorkSpace_vim/rrt$ git submodule update --init
travis-byun@HCI:~/WorkSpace_vim/rrt$ make
mkdir -p build
cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH="" -GNinja && ninja
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
CMake Error:
  The detected version of Ninja (log: ninja version 0.1.3 initializing) is
  less than the version of Ninja required by CMake (1.3).


CMake Error: Internal CMake error, TryCompile generation of cmake failed
-- Check for working C compiler using: Ninja -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home/travis-byun/WorkSpace_vim/rrt/build/CMakeFiles/CMakeOutput.log".
See also "/home/travis-byun/WorkSpace_vim/rrt/build/CMakeFiles/CMakeError.log".
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by pioneerbkh** [comment]
travis-byun@HCI:~/WorkSpace_vim/rrt$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../.ICEauthority
	../../.Xauthority
	../../.android/
	../../.arduino15/
	../../.bash_history
	../../.bash_logout
	../../.bashrc
	../../.bzr.log
	../../.cache/
	../../.compiz/
	../../.config/
	../../.dbus/
	../../.designer/
	../../.dmrc
	../../.gazebo/
	../../.gnome/
	../../.java/
	../../.lesshst
	../../.local/
	../../.matlab/
	../../.mozilla/
	../../.oracle_jre_usage/
	../../.pki/
	../../.presage/
	../../.profile
	../../.ros/
	../../.rviz/
	../../.sdformat/
	../../.selected_editor
	../../.ssh/
	../../.ssr/
	../../.subversion/
	../../.sudo_as_admin_successful
	../../.vim/
	../../.viminfo
	../../.vimrc
	../../.vnc/
	../../.xinputrc
	../../.xsession-errors
	../../.xsession-errors.old
	../../0708-2016-07-08_13.32.39.mkv
	../../Arduino/
	../../Desktop/
	../../Documents/
	../../Downloads/
	../../LeddarSDK3.2.0_x86_64/
	../../Pictures/
	../../Qt5.7.0/
	../../WorkSpace_QT/
	../../WorkSpace_matlab/
	../
	../../arduino-1.6.9/
	../../bluetooth.conf
	../../catkin_ws/
	../../conf.sh
	../../installer_input.txt
	../../lldb-mi-log.txt
	../../mrpt-1.4.0.tar.gz
	../../mrpt-1.4.0/
	../../opencv-2.4.13/
	../../project_src/
	../../px4/
	../../qwt-6.1.3.tar.bz2
	../../qwt-6.1.3/
	../../urg_library-1.0.4.tar.gz
	../../urg_library-1.0.4/

nothing added to commit but untracked files present (use "git add" to track)
travis-byun@HCI:~/WorkSpace_vim/rrt$ git submodule

**Comment by jgkamat** [comment]
Hmm, this is pretty weird. Can you try deleting the rrt folder and recloning it with 
`git clone https://github.com/RoboJackets/rrt.git`?

after you do that, cd inside the newly created rrt folder, run `git submodule update --init` and `make`

**Comment by jgkamat** [comment]
Also, can you ensure you have the `ninja-build` package installed:

`sudo apt install ninja-build` (You are on ubuntu 16.04, correct?)

**Comment by pioneerbkh** [comment]
That's right.
I followed your solution but it's still unnatural.
It's same as before.
I can not form any idea of what it is.

**Comment by jgkamat** [comment]
Can you run the following commands, which should set up a new rrt repo properly configured in your /tmp folder

`sudo apt install ninja-build qt5-default libeigen3-dev`
`cd /tmp`
`git clone https://github.com/RoboJackets/rrt.git`
`cd rrt`
`git submodule sync`
`git submodule update --init`
`make`

and report the output of any of these steps if it fails?

**Comment by pioneerbkh** [comment]
I got this messages.

travis-byun@HCI:~$ sudo apt install ninja-build qt5-default libeigen3-dev
[sudo] password for travis-byun: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libeigen3-dev is already the newest version (3.3~beta1-2).
ninja-build is already the newest version (1.5.1-0.1ubuntu1).
qt5-default is already the newest version (5.5.1+dfsg-16ubuntu7.2).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
travis-byun@HCI:~$ cd /tmp
travis-byun@HCI:/tmp$ git clone https://github.com/RoboJackets/rrt.git
Cloning into 'rrt'...
remote: Counting objects: 1970, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1970 (delta 0), reused 0 (delta 0), pack-reused 1965
Receiving objects: 100% (1970/1970), 1.53 MiB | 399.00 KiB/s, done.
Resolving deltas: 100% (1177/1177), done.
Checking connectivity... done.
travis-byun@HCI:/tmp$ cd rrt
travis-byun@HCI:/tmp/rrt$ git submodule sync
travis-byun@HCI:/tmp/rrt$ git submodule update --init
Submodule 'third_party/DoCIF' (https://github.com/jgkamat/DoCIF) registered for path 'third_party/DoCIF'
Submodule 'third_party/googletest' (https://github.com/google/googletest) registered for path 'third_party/googletest'
Submodule 'third_party/style-configs' (https://github.com/robojackets/style-configs) registered for path 'third_party/style-configs'
Cloning into 'third_party/DoCIF'...
remote: Counting objects: 885, done.
remote: Total 885 (delta 0), reused 0 (delta 0), pack-reused 885
Receiving objects: 100% (885/885), 132.72 KiB | 176.00 KiB/s, done.
Resolving deltas: 100% (486/486), done.
Checking connectivity... done.
Submodule path 'third_party/DoCIF': checked out 'b916e5505bdf27babcaf28c1bb9085ede77b4ef2'
Cloning into 'third_party/googletest'...
remote: Counting objects: 7422, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 7422 (delta 4), reused 0 (delta 0), pack-reused 7407
Receiving objects: 100% (7422/7422), 2.52 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (5512/5512), done.
Checking connectivity... done.
Submodule path 'third_party/googletest': checked out '43359642a1c16ad3f4fc575c7edd0cb935810815'
Cloning into 'third_party/style-configs'...
remote: Counting objects: 15, done.
remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (15/15), done.
Checking connectivity... done.
Submodule path 'third_party/style-configs': checked out '90cc111f04dc1baee0a99f75a5c850282b54bcde'
travis-byun@HCI:/tmp/rrt$ make
mkdir -p build
cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH="" -GNinja && ninja
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Eigen: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found Qt5: /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/rrt/build
[7/14] Building CXX object CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o -c ../src/rrt/2dplane/2dplane.cpp
/bin/sh: 1: ccache: not found
[7/14] Building CXX object CMakeFiles/...r/src/rrt/2dplane/GridStateSpace.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o -c ../src/rrt/2dplane/GridStateSpace.cpp
/bin/sh: 1: ccache: not found
[7/14] Building CXX object CMakeFiles/RRT.dir/RRT_automoc.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/RRT_automoc.cpp.o -MF CMakeFiles/RRT.dir/RRT_automoc.cpp.o.d -o CMakeFiles/RRT.dir/RRT_automoc.cpp.o -c RRT_automoc.cpp
/bin/sh: 1: ccache: not found
[7/14] Building CXX object CMakeFiles/...dir/src/rrt/2dplane/ObstacleGrid.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o -c ../src/rrt/2dplane/ObstacleGrid.cpp
/bin/sh: 1: ccache: not found
[7/14] Automatic moc for target rrt-viewer
Generating moc_MainWindow.cpp
Generating moc_RRTWidget.cpp
ninja: build stopped: subcommand failed.
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
travis-byun@HCI:/tmp/rrt$ make run
mkdir -p build
cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH="" -GNinja && ninja
-- Found Qt5: /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/rrt/build
[6/13] Building CXX object CMakeFiles/...r/src/rrt/2dplane/GridStateSpace.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/GridStateSpace.cpp.o -c ../src/rrt/2dplane/GridStateSpace.cpp
/bin/sh: 1: ccache: not found
[6/13] Building CXX object CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/2dplane.cpp.o -c ../src/rrt/2dplane/2dplane.cpp
/bin/sh: 1: ccache: not found
[6/13] Building CXX object CMakeFiles/...dir/src/rrt/2dplane/ObstacleGrid.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o -MF CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o.d -o CMakeFiles/RRT.dir/src/rrt/2dplane/ObstacleGrid.cpp.o -c ../src/rrt/2dplane/ObstacleGrid.cpp
/bin/sh: 1: ccache: not found
[6/13] Building CXX object CMakeFiles/RRT.dir/RRT_automoc.cpp.o
FAILED: ccache /usr/bin/c++    -I. -I../ -I../src -isystem /usr/include/eigen3 -Igoogletest-prefix/src/googletest/include -std=c++11 -fPIC -g -MMD -MT CMakeFiles/RRT.dir/RRT_automoc.cpp.o -MF CMakeFiles/RRT.dir/RRT_automoc.cpp.o.d -o CMakeFiles/RRT.dir/RRT_automoc.cpp.o -c RRT_automoc.cpp
/bin/sh: 1: ccache: not found
ninja: build stopped: subcommand failed.
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by jgkamat** [comment]
perfect, I think we almost have it set up! Can you try running `sudo apt install ccache`?

I think we need to add that to the README, we forgot about that. Once you have that installed, could you try running `make run` in `/tmp/rrt` and see if that fixes compiles?

**Comment by pioneerbkh** [comment]
Finally, I solved the problem what I got.
I lost or don't have ccache.
sudo apt-get install -y ccache &&\
echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc &&\
source ~/.bashrc && echo $PATH

**Comment by pioneerbkh** [comment]
Thanks a lot.

It works.

**Comment by jgkamat** [comment]
Thanks for trying this out! let us know if you run into any other issues :smile:
