### ISSUE TITLE
Can you explain what the theory you adopted?

### ISSUE THREAD

**Issue by pioneerbkh** [RoboJackets/rrt#48]
For academic approach, Can you explain more details about what the theory you adopted in your code?

like:
Path Generation: Batch informed trees(BIT*).
Path smoothing: Single Polar Polynomial(SPP) curve or Clothoid curve.
some others: 

Thank for your help.

**Comment by jgkamat** [comment]
@joshhting do you think you could take a stab at this? I think it would be great to create a docs page with more high level information about the RRT setup.

We have a set of overview slides we used this year for [training here](https://robojackets.github.io/robocup-training/slides/6#/sec-title-slide), which might be helpful.

For path generation we use two RRT's, which expand from the desired start and end points, and once they collide, we use the branches that collided as a rough path.

Once that is done, we apply a bezier curve to the rough path to smooth it out. When we do this path smoothing, we also do some checks to make sure the smooth path does not take us through obstacles.

**Comment by pioneerbkh** [comment]
Thank you for your kindness.
