### ISSUE TITLE
RRT places obstacles before the first click

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/rrt#49]
Dragging the mouse around before the first click is made causes obstacles to be added. 

After the first click, everything is fine.

This can be solved by adding `_editingObstacles = false;` [to this file in the constructor](https://github.com/RoboJackets/rrt/blob/master/src/rrt-viewer/RRTWidget.cpp#L33)

**Comment by kevinatorchen** [comment]
My issue. Mine only.
