### ISSUE TITLE
Potential Error in Grid Square Location Computation

### ISSUE THREAD

**Issue by SiyuanQi** [RoboJackets/rrt#55]
In the `gridSquareForLocation` function of class ObstacleGrid here:
[original code](https://github.com/RoboJackets/rrt/blob/master/src/rrt/2dplane/ObstacleGrid.cpp#L25-L28)

Shouldn't the result be the following?
```cpp
    return Vector2i(loc.x() / discretizedWidth(),
                    loc.y() / discretizedHeight());
```

As I understand the code, `width` and `height` refers to the size of the whole space. `discretizedWidth` and `discretizedHeight` refers the to the size of the grids. Correct me if I am wrong. Thank you!

**Comment by SiyuanQi** [comment]
I just realize that `discretizedWidth` and `discretizedHeight` refers the to the size of the grids. Never mind!

**Comment by jgkamat** [comment]
Hi! Glad you're taking a look at our codebase! One of the reasons you might be confused is that we have little documentation (and we don't have a docs site for the rrt, as our other projects do). I'm opening a new issue to try to get more docs and a docs site up.

Thanks for taking the time to look at our rrt! :smile:
