### ISSUE TITLE
Path can go through obstacle corners

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/rrt#63]
Path should not go through obstacle corners

**Comment by kevinatorchen** [comment]
![image](https://cloud.githubusercontent.com/assets/13036299/22629349/45b05830-ebb2-11e6-8331-a54d6fd5e27c.png)

**Comment by joshhting** [comment]
To be clear, this isn't an issue with the tree stepping over the obstacle, it's an issue with the two RRTs thinking they're connected even if there's an obstacle between them.
![screenshot from 2017-02-05 14-53-37](https://cloud.githubusercontent.com/assets/8889217/22629406/52582bfc-ebb3-11e6-9aef-c586948baaed.png)
