### ISSUE TITLE
Main.qml not found on ubuntu 16.04

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/rrt#67]
Regression in switching to qtquick/qtdelcarative/qml.

I'll fix this. Most likeley we'll just need to downgrade our qml versions.

Ubuntu 16.04 uses qt 5.4.

This is a regresssion in #54

**Comment by Jason27chan** [comment]
Error:
QQmlApplicationEngine failed to load component
file:///home/vagrant/path-planning/:/main.qml:-1 File not found

Segmentation fault (core dumped)

**Comment by jgkamat** [comment]
We'll also need to drop 14.04 support (which I suppose is fine for the RRT).

**Comment by jgkamat** [comment]
Closed in #68
